### ISSUE TITLE
API Returning Blank Values

### ISSUE THREAD

**Issue by PatrickCroke** [bZxNetwork/bzx-api#19]
Attempted to get data for TVL-history and Asset-stats-history. I was returning blank values using https://api.bzx.network/#/History%20Data/get_tvl_history

![Screen Shot 2021-05-30 at 2 36 53 PM](https://user-images.githubusercontent.com/50606705/120116112-894ef980-c154-11eb-88ea-bc79f3c06375.png)

![Screen Shot 2021-05-30 at 2 37 40 PM](https://user-images.githubusercontent.com/50606705/120116126-9835ac00-c154-11eb-8095-29062b33b109.png)

**Comment by Kharabet** [comment]
Dates should be passed in milliseconds, not in seconds. 
So, instead of 1612031424 you should pass 1612031424000 (Jan 30 2021) and the same for 1622399279000 (May 30 2021)

Final request url should be `https://api.bzx.network/v1/tvl-history?networks=eth%2Cbsc&start_date=1612031424000&end_date=1622399279000&points_number=100`

**Comment by Kharabet** [comment]
> Attempted to get data for TVL-history and Asset-stats-history. I was returning blank values using https://api.bzx.network/#/History%20Data/get_tvl_history
> 
> ![Screen Shot 2021-05-30 at 2 36 53 PM](https://user-images.githubusercontent.com/50606705/120116112-894ef980-c154-11eb-88ea-bc79f3c06375.png)
> 
> ![Screen Shot 2021-05-30 at 2 37 40 PM](https://user-images.githubusercontent.com/50606705/120116126-9835ac00-c154-11eb-8095-29062b33b109.png)

Sorry for the late response. Feel free to reopen the issue if it didn't help to resolve your issue
